import assert from "node:assert/strict";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";
import type { JSONSchema4 } from "json-schema";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const inventoryPath = path.join(repositoryRoot, "contracts/v1/inventory.json");
const schemaDirectory = path.join(repositoryRoot, "contracts/v1/schemas");
const generatedTypesPath = path.join(repositoryRoot, "src/schemas/v1/artifacts.generated.ts");

const generatedBanner = `/**
 * Generated from contracts/v1/schemas by scripts/generate-schema-types.ts.
 * Do not edit this file by hand; edit the checked-in JSON Schema source and regenerate it.
 */`;

type ContractInventory = {
  readonly contracts?: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function readJson(filePath: string): Promise<unknown> {
  return JSON.parse(await readFile(filePath, "utf8")) as unknown;
}

export async function inventoryArtifactSchemaPaths(): Promise<readonly string[]> {
  const inventory: ContractInventory = (await readJson(inventoryPath)) as ContractInventory;
  assert.ok(Array.isArray(inventory.contracts), "inventory.contracts must be an array");

  return inventory.contracts
    .filter((contract) => isRecord(contract) && contract.category === "artifact")
    .map((contract) => {
      assert.ok(
        isRecord(contract) && typeof contract.materialized_schema === "string",
        "every inventory artifact contract must name a materialized_schema",
      );
      return contract.materialized_schema;
    });
}

function schemaFilename(schemaPath: string): string {
  const absolutePath = path.resolve(repositoryRoot, schemaPath);
  assert.equal(
    path.dirname(absolutePath),
    schemaDirectory,
    `artifact schema must be directly under contracts/v1/schemas: ${schemaPath}`,
  );
  assert.ok(schemaPath.endsWith(".schema.json"), `artifact schema must be a .schema.json file: ${schemaPath}`);
  return path.basename(absolutePath);
}

function collectReferences(value: unknown, references: string[]): void {
  if (Array.isArray(value)) {
    for (const item of value) collectReferences(item, references);
    return;
  }
  if (!isRecord(value)) return;

  if (typeof value.$ref === "string") references.push(value.$ref);
  for (const child of Object.values(value)) collectReferences(child, references);
}

function assertJsonPointerResolves(schema: unknown, fragment: string, reference: string): void {
  if (fragment === "") return;
  assert.ok(fragment.startsWith("/"), `schema ref fragment must be a JSON Pointer: ${reference}`);

  let current = schema;
  for (const encodedSegment of fragment.slice(1).split("/")) {
    const segment = decodeURIComponent(encodedSegment).replaceAll("~1", "/").replaceAll("~0", "~");
    assert.ok(isRecord(current) || Array.isArray(current), `schema ref does not resolve: ${reference}`);
    assert.ok(Object.hasOwn(current, segment), `schema ref does not resolve: ${reference}`);
    current = current[segment as keyof typeof current];
  }
}

export async function assertLocalSchemaReferencesResolve(schemaPaths: readonly string[]): Promise<void> {
  const pending = schemaPaths.map(schemaFilename);
  const visited = new Set<string>();

  while (pending.length > 0) {
    const filename = pending.shift();
    assert.ok(filename !== undefined);
    if (visited.has(filename)) continue;
    visited.add(filename);

    const schema = await readJson(path.join(schemaDirectory, filename));
    const references: string[] = [];
    collectReferences(schema, references);
    for (const reference of references) {
      const hashIndex = reference.indexOf("#");
      const referencedFile = hashIndex === -1 ? reference : reference.slice(0, hashIndex);
      const fragment = hashIndex === -1 ? "" : reference.slice(hashIndex + 1);
      assert.ok(!path.isAbsolute(referencedFile), `non-local schema ref: ${reference}`);
      const resolvedPath: string =
        referencedFile === "" ? path.join(schemaDirectory, filename) : path.resolve(schemaDirectory, referencedFile);
      assert.equal(
        path.dirname(resolvedPath),
        schemaDirectory,
        `schema ref escapes the schema directory: ${reference}`,
      );
      const referencedSchema = await readJson(resolvedPath);
      assertJsonPointerResolves(referencedSchema, fragment, reference);
      pending.push(path.basename(resolvedPath));
    }
  }
}

export async function generateArtifactTypes(): Promise<string> {
  const schemaPaths = await inventoryArtifactSchemaPaths();
  assert.ok(schemaPaths.length > 0, "inventory must materialize at least one artifact schema");
  assert.equal(new Set(schemaPaths).size, schemaPaths.length, "inventory artifact schema paths must be unique");
  await assertLocalSchemaReferencesResolve(schemaPaths);

  const aggregateSchema: JSONSchema4 = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Version1Artifact",
    anyOf: schemaPaths.map((schemaPath) => ({ $ref: schemaFilename(schemaPath) })),
  };

  return compile(aggregateSchema, "version-1-artifact.schema.json", {
    additionalProperties: true,
    bannerComment: generatedBanner,
    cwd: schemaDirectory,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    format: true,
    strictIndexSignatures: true,
    style: {
      bracketSpacing: true,
      printWidth: 120,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      useTabs: false,
    },
    unknownAny: true,
  });
}

export async function writeArtifactTypes(): Promise<void> {
  await writeFile(generatedTypesPath, await generateArtifactTypes(), "utf8");
}

export async function checkArtifactTypes(): Promise<void> {
  const expected = await generateArtifactTypes();
  const actual = await readFile(generatedTypesPath, "utf8");
  assert.equal(actual, expected, "generated artifact types are stale; run npm run generate:schemas");

  const generatedFiles = (await readdir(path.dirname(generatedTypesPath)))
    .filter((filename) => filename.endsWith(".generated.ts"))
    .sort();
  assert.deepEqual(generatedFiles, [path.basename(generatedTypesPath)], "unexpected generated schema type output");
}

async function main(): Promise<void> {
  const [command, ...unexpectedArguments] = process.argv.slice(2);
  assert.equal(unexpectedArguments.length, 0, "schema type generator accepts exactly one command");
  if (command === "--write") {
    await writeArtifactTypes();
    console.log(`Generated ${path.relative(repositoryRoot, generatedTypesPath)}`);
    return;
  }
  if (command === "--check") {
    await checkArtifactTypes();
    console.log("Generated schema types are current");
    return;
  }
  throw new Error("usage: node scripts/generate-schema-types.ts --write|--check");
}

const invokedPath = process.argv[1] === undefined ? undefined : path.resolve(process.argv[1]);
if (invokedPath === fileURLToPath(import.meta.url)) await main();
