/**
 * Generated from contracts/v1/schemas by scripts/generate-schema-types.ts.
 * Do not edit this file by hand; edit the checked-in JSON Schema source and regenerate it.
 */

export type Version1Artifact =
  | SDDYoChangeDescriptor
  | SDDYoUserSkillInstallation
  | SDDYoCandidateTreeManifest
  | SDDYoProposalPackage
  | SDDYoSpecPatch
  | SDDYoApprovalEvidence
  | SDDYoTestIndex
  | SDDYoTestExecutionEvidence
  | SDDYoQAEvidence
  | SDDYoGovernanceEvidence
  | SDDYoFinding
  | SDDYoFindingResolution
  | SDDYoHumanSemanticReviewEvidence
  | SDDYoSemanticAnalysisInputManifest
  | SDDYoConflictReport
  | SDDYoVerificationReport
  | SDDYoMergeReport;
/**
 * Version 1 transient input describing an approved synchronization change.
 */
export type SDDYoChangeDescriptor = ArtifactEnvelope & {
  [k: string]: unknown | undefined;
} & {
  artifact_type?: "change_descriptor";
  mode: "spec-code" | "spec" | "code";
  integration_ref: string;
  proposal_ref: string;
  approved_delta: ApprovedDelta;
  code_targets: CodeTarget[];
  [k: string]: unknown | undefined;
};
/**
 * @minItems 1
 */
export type FileInventory = [FileEntry, ...FileEntry[]];
/**
 * Version 1 candidate specification tree retained only as a fixed proposal-bundle member.
 */
export type SDDYoCandidateTreeManifest = ArtifactEnvelope & {
  artifact_type?: "candidate_tree_manifest";
  base_tree_fingerprint: string;
  files: {
    path: string;
    sha256: string;
    content_utf8: string;
  }[];
  [k: string]: unknown | undefined;
};
/**
 * Version 1 deterministic Proposal Gate output.
 */
export type SDDYoProposalPackage = ArtifactEnvelope & {
  [k: string]: unknown | undefined;
} & {
  artifact_type?: "proposal_package";
  mode: "spec-code" | "spec" | "code";
  base: Base;
  candidate: Candidate;
  object_delta: ObjectDelta;
  code_targets: CodeTargets;
  affected_scope: AffectedScope;
  diagnostics: Diagnostic[];
  semantic_candidates: SemanticCandidate[];
  [k: string]: unknown | undefined;
};
export type ObjectIds = string[];
export type CodeTargets = CodeTarget[];
export type RequirementIds = string[];
export type CapabilityIds = string[];
/**
 * Version 1 exact specification file operations.
 */
export type SDDYoSpecPatch = ArtifactEnvelope & {
  artifact_type?: "spec_patch";
  base_tree_fingerprint: string;
  result_tree_fingerprint: string;
  operations: (
    | (OperationBase & {
        operation: "create";
        path: unknown;
        after_sha256: string;
        content_utf8: string;
      })
    | (OperationBase & {
        operation: "replace";
        path: unknown;
        before_sha256: string;
        after_sha256: string;
        content_utf8: string;
      })
    | (OperationBase & {
        operation: "delete";
        path: unknown;
        before_sha256: string;
      })
  )[];
  [k: string]: unknown | undefined;
};
/**
 * Version 1 external product approval decision.
 */
export type SDDYoApprovalEvidence = ArtifactEnvelope & {
  artifact_type?: "approval_evidence";
  issuer: string;
  actor: string;
  decision: "approved" | "rejected";
  mode: "spec-code" | "spec" | "code";
  subject: {
    base: Base;
    candidate: Candidate;
    object_delta: ObjectDelta;
    code_targets: CodeTargets;
    affected_scope: AffectedScope;
  };
  reason?: string;
  [k: string]: unknown | undefined;
};
/**
 * Version 1 normalized executable test discovery snapshot.
 */
export type SDDYoTestIndex = ArtifactEnvelope & {
  artifact_type?: "test_index";
  subject: {
    head_ref: string;
    config_fingerprint: string;
    adapter_fingerprints: {
      [k: string]: string;
    };
  };
  tests: {
    test_ref: string;
    adapter_id: string;
    local_id: string;
    full_name: string;
    requirement_ids: string[];
    source?: SourceLocation;
  }[];
  [k: string]: unknown | undefined;
};
/**
 * Version 1 external executable test result evidence.
 */
export type SDDYoTestExecutionEvidence = ArtifactEnvelope & {
  artifact_type?: "test_execution_evidence";
  issuer: string;
  subject: {
    head_ref: string;
    test_index_fingerprint: string;
    config_fingerprint: string;
  };
  results: {
    test_ref: string;
    status: "passed" | "failed" | "skipped" | "todo" | "disabled" | "xfailed" | "error";
    duration_ms?: number;
  }[];
  [k: string]: unknown | undefined;
};
/**
 * Version 1 external QA and manual Requirement decision evidence.
 */
export type SDDYoQAEvidence = ArtifactEnvelope & {
  artifact_type?: "qa_evidence";
  issuer: string;
  actor: string;
  decision: "passed" | "failed";
  subject: {
    head_ref: string;
    integration_ref: string;
    affected_scope_fingerprint: string;
  };
  capability_ids: string[];
  manual_requirements: {
    requirement_id: string;
    decision: "passed" | "failed";
  }[];
  notes?: string;
  [k: string]: unknown | undefined;
};
/**
 * Version 1 external project adoption transition decision.
 */
export type SDDYoGovernanceEvidence = ArtifactEnvelope & {
  [k: string]: unknown | undefined;
} & {
  artifact_type?: "governance_evidence";
  issuer: string;
  actor: string;
  decision: "approved" | "rejected";
  subject: {
    config_fingerprint: string;
    project_scope_fingerprint: string;
    from_adoption_mode: "incremental" | "complete";
    to_adoption_mode: "incremental" | "complete";
  };
  reason?: string;
  [k: string]: unknown | undefined;
};
/**
 * Version 1 evidence-backed semantic or quality finding.
 */
export type SDDYoFinding = ArtifactEnvelope & {
  [k: string]: unknown | undefined;
} & {
  artifact_type?: "finding";
  finding_id: string;
  analyzer: Analyzer;
  kind: "semantic_conflict" | "quality";
  severity: "blocking" | "review";
  input_fingerprint: string;
  /**
   * @minItems 1
   */
  objects: [string, ...string[]];
  /**
   * @minItems 1
   */
  sections: [
    {
      object_id: string;
      section: "statement" | "acceptance" | "constraints" | "definition" | "identity" | "states" | "relations";
    },
    ...{
      object_id: string;
      section: "statement" | "acceptance" | "constraints" | "definition" | "identity" | "states" | "relations";
    }[],
  ];
  summary: string;
  confidence: number;
  waiver_eligible: boolean;
  [k: string]: unknown | undefined;
};
/**
 * Version 1 external human decision for one exact Finding input.
 */
export type SDDYoFindingResolution = ArtifactEnvelope & {
  artifact_type?: "finding_resolution";
  issuer: string;
  actor: string;
  finding_id: string;
  input_fingerprint: string;
  decision: "dismissed" | "waived" | "confirmed";
  reason: string;
  [k: string]: unknown | undefined;
};
/**
 * Version 1 human review evidence for a deterministic candidate set.
 */
export type SDDYoHumanSemanticReviewEvidence = ArtifactEnvelope & {
  artifact_type?: "human_semantic_review_evidence";
  issuer: string;
  actor: string;
  decision: "reviewed";
  candidate_input_fingerprint: string;
  finding_ids: string[];
  [k: string]: unknown | undefined;
};
/**
 * Version 1 fingerprint-bound semantic analysis context manifest.
 */
export type SDDYoSemanticAnalysisInputManifest = ArtifactEnvelope & {
  artifact_type?: "semantic_analysis_input_manifest";
  analyzer: Analyzer;
  input_fingerprint: string;
  changed_objects: ObjectIds1;
  related_objects: ObjectIds1;
  normative_sections: {
    object_id: string;
    section: "statement" | "acceptance" | "constraints" | "definition" | "identity" | "states" | "relations";
    content: string;
  }[];
  candidate_reasons: SemanticCandidate[];
  [k: string]: unknown | undefined;
};
export type ObjectIds1 = string[];
/**
 * Version 1 three-way mechanical and semantic conflict analysis.
 */
export type SDDYoConflictReport = ArtifactEnvelope & {
  artifact_type?: "conflict_report";
  integration_ref: string;
  branch_head: string;
  merge_base: string;
  config_fingerprint: string;
  mechanical_conflicts: {
    path: string;
    kind: "add_add" | "modify_modify" | "modify_delete" | "delete_modify" | "id_reuse";
    object_id?: string;
  }[];
  semantic_candidates: SemanticCandidate[];
  input_fingerprint: string;
  [k: string]: unknown | undefined;
};
/**
 * Version 1 deterministic Verification Gate output.
 */
export type SDDYoVerificationReport = ArtifactEnvelope & {
  artifact_type?: "verification_report";
  head_ref: string;
  integration_ref: string;
  config_fingerprint: string;
  affected_scope_fingerprint: string;
  affected_requirements: RequirementIds1;
  affected_capabilities: CapabilityIds1;
  test_coverage: RequirementCheck;
  test_execution: RequirementCheck;
  manual_verification: RequirementCheck;
  qa_coverage: CapabilityCheck;
  findings: FindingSummary[];
  status: "PASS" | "REVIEW_REQUIRED" | "BLOCKED";
  diagnostics: Diagnostic[];
  [k: string]: unknown | undefined;
};
export type RequirementIds1 = string[];
export type CapabilityIds1 = string[];
/**
 * Version 1 deterministic Merge Gate readiness report.
 */
export type SDDYoMergeReport = ArtifactEnvelope & {
  [k: string]: unknown | undefined;
} & {
  artifact_type?: "merge_report";
  integration_ref: string;
  branch_head: string;
  merge_base: string;
  config_fingerprint: string;
  mode: "spec-code" | "spec" | "code";
  deltas_or_code_targets: {
    approved_delta?: ApprovedDelta;
    /**
     * @minItems 1
     */
    code_targets?: [CodeTarget, ...CodeTarget[]];
  };
  affected_scope: {
    fingerprint: string;
    requirements: RequirementIds2;
    capabilities: CapabilityIds2;
  };
  test_summary: CheckSummary;
  qa_summary: CheckSummary;
  findings_and_evidence: {
    findings: FindingSummary[];
    evidence_status: "current" | "missing" | "stale" | "negative" | "contradictory";
  };
  adoption: {
    mode: "incremental" | "complete";
    project_scope_fingerprint: string;
  };
  diagnostics: Diagnostic[];
  status: "PASS" | "REVIEW_REQUIRED" | "BLOCKED";
  /**
   * @minItems 1
   */
  input_manifest: [
    {
      artifact_type: string;
      fingerprint: string;
      source: "stdin" | string;
    },
    ...{
      artifact_type: string;
      fingerprint: string;
      source: "stdin" | string;
    }[],
  ];
  [k: string]: unknown | undefined;
};
export type RequirementIds2 = string[];
export type CapabilityIds2 = string[];

export interface ArtifactEnvelope {
  schema_version: "1.0";
  artifact_type: string;
  project_id: string;
  created_at?: string;
  producer?: Producer;
  [k: string]: unknown | undefined;
}
export interface Producer {
  name: string;
  version: string;
}
export interface ApprovedDelta {
  semantic: string;
  structural: string;
}
export interface CodeTarget {
  requirement_id: string;
  semantic_fingerprint: string;
  structural_fingerprint: string;
}
/**
 * Version 1 owned macOS user-scoped Skill and private CLI installation binding.
 */
export interface SDDYoUserSkillInstallation {
  schema_version: "1.0";
  artifact_type: "sdd_yo_user_skill_installation";
  scope: "user";
  package: PackageIdentity;
  cli: CliIdentity;
  json_schema: JsonSchemaIdentity;
  skill: SkillIdentity;
  package_fingerprint: string;
  package_files: FileInventory;
  skill_files: FileInventory;
}
export interface PackageIdentity {
  name: "sdd-yo";
  version: string;
}
export interface CliIdentity {
  name: "sdd";
  version: string;
  path: string;
}
export interface JsonSchemaIdentity {
  version: "1.0";
  compatible_major: 1;
}
export interface SkillIdentity {
  name: "sdd-yo";
  protocol_version: "1.0";
  compatible_major: 1;
  payload_fingerprint: string;
}
export interface FileEntry {
  path: string;
  sha256: string;
}
export interface Base {
  git_ref: string;
  tree_fingerprint: string;
}
export interface Candidate {
  source: "base" | "manifest";
  tree_fingerprint: string;
}
export interface ObjectDelta {
  semantic_fingerprint: string;
  structural_fingerprint: string;
  added: ObjectIds;
  modified: ObjectIds;
  deleted: ObjectIds;
}
export interface AffectedScope {
  fingerprint: string;
  requirements: RequirementIds;
  capabilities: CapabilityIds;
}
export interface Diagnostic {
  code: string;
  severity: "info" | "warning" | "error";
  message: string;
  location?: SourceLocation;
  object_id?: string;
  details: {
    [k: string]: unknown | undefined;
  };
}
export interface SourceLocation {
  path: string;
  line?: number;
  column?: number;
}
export interface SemanticCandidate {
  /**
   * @minItems 1
   */
  objects: [string, ...string[]];
  reason: string;
}
export interface OperationBase {
  operation: "create" | "replace" | "delete";
  path: string;
  [k: string]: unknown | undefined;
}
export interface Analyzer {
  name: string;
  version: string;
}
export interface RequirementCheck {
  satisfied: RequirementIds1;
  unsatisfied: RequirementIds1;
}
export interface CapabilityCheck {
  satisfied: CapabilityIds1;
  unsatisfied: CapabilityIds1;
}
export interface FindingSummary {
  finding_id: string;
  state: "open" | "resolved" | "stale" | "contradictory";
}
export interface CheckSummary {
  status: "PASS" | "REVIEW_REQUIRED" | "BLOCKED" | "NOT_APPLICABLE";
  satisfied: number;
  unsatisfied: number;
}
